version: '3.8'

services:
  db:
    container_name: tweetapp_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tweetapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"

  web:
    container_name: tweetapp_web
    image: tweetapp:development
    volumes:
      - .:/rails
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DATABASE_URL: postgres://postgres:password@db:5432/tweetapp
    command: bash -c "bundle exec rails db:create db:migrate db:seed && ./bin/thrust ./bin/rails server -b 0.0.0.0"

volumes:
  postgres_data: